 # This is a basic workflow to help you get started with Actions

name: Data sharing between jobs

# Controls when the workflow will run
on: [push]

jobs:

  job_1:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: 
          cal 2022 > calendar.txt
      - name: Upload the cal.txt file
        uses: actions/upload-artifact@v3
        with:
          name: calendar
          path: calendar.txt
 
  job_2:
    name: Download file
    needs: [job_1]
    runs-on: windows-latest
    steps:
      - name: Download the cal.txt file
        uses: actions/download-artifact@v3
        with:
          name: calendar
          path: calendar.txt
