# To understand user defined variables 

name: User Defined Variables

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
env:
  firstName: Tony
  lastName: Skillman


# Read User Defined Variables from environment
jobs:
  windows_job:
    runs-on:
      windows-latest
    steps:
      - name: Display firstName variable
        run: echo "Hi ${{env.firstName}}"
      - name: Display lastName variable
        run: echo "Hi ${{env.lastName}}"
      - name: Display job
        run: echo "${{job}}"
        env:
          job: "Developer"
        
  ubuntu_job:
    runs-on:
      ubuntu-latest
    steps:
      - name: Display env variables
        run: echo "Hi ${{env.lastName}}"
